jail:
  server: "jail"
japanizer: true
Discord:
  Token: ""
  Guild:
  ChatChannel:
  SystemChannel:
  LogChannel:
  NotificationChannel:
  AdminChannel:

MySQL:
  Host: localhost
  User: root
  Password: ""
  Port: 3306
  SSL: true
  Database: man10_system

BlockAutoMessages:
  - "Connected with MineChat" # MineChat
  - "I joined using ChatCraft from my Android device! Download it for free!" # Android ChatCraft
  - "I joined using ChatCraft from my iOS device! Download it for free!" # iOS ChatCraft

Broadcast:
  - "お久しぶりです。みんな大好きMHKですよーん! (受信料くれ)"
  - "M◯Kをぶっ壊す!"
  - "MHKはみんなに夢と希望を与える素晴らしいものなんだよ！"